# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mainpage1


class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.describ_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.describ_text.setObjectName("describ_text")
        self.gridLayout.addWidget(self.describ_text, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 238, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 5, 1)
        self.link_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.link_text.setObjectName("link_text")
        self.gridLayout.addWidget(self.link_text, 3, 1, 1, 1)
        self.market_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.market_text.setObjectName("market_text")
        self.gridLayout.addWidget(self.market_text, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 4, 1)
        self.price_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.price_text.setObjectName("price_text")
        self.gridLayout.addWidget(self.price_text, 1, 1, 2, 1)
        self.add_to_cart = QtWidgets.QPushButton(self.centralwidget)
        self.add_to_cart.setMinimumSize(QtCore.QSize(40, 40))
        self.add_to_cart.setMaximumSize(QtCore.QSize(40, 40))
        self.add_to_cart.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Icn1001715www.tiktarh.com_.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_cart.setIcon(icon)
        self.add_to_cart.setIconSize(QtCore.QSize(40, 40))
        self.add_to_cart.setObjectName("add_to_cart")
        self.gridLayout.addWidget(self.add_to_cart, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.add_to_cart.clicked.connect(self.add_to_cart.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "صفحه نتایج"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.add_to_cart.setText(_translate("MainWindow", " "))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
'''